//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 12/7/2012 3:23:52 PM
namespace DataFeedsVinControlConversion.OldDatabaseModel
{
    
    /// <summary>
    /// There are no comments for whitmanenterprisewarehouseEntities1 in the schema.
    /// </summary>
    public partial class whitmanenterprisewarehouseEntities1 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new whitmanenterprisewarehouseEntities1 object using the connection string found in the 'whitmanenterprisewarehouseEntities1' section of the application configuration file.
        /// </summary>
        public whitmanenterprisewarehouseEntities1() : 
                base("name=whitmanenterprisewarehouseEntities1", "whitmanenterprisewarehouseEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new whitmanenterprisewarehouseEntities1 object.
        /// </summary>
        public whitmanenterprisewarehouseEntities1(string connectionString) : 
                base(connectionString, "whitmanenterprisewarehouseEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new whitmanenterprisewarehouseEntities1 object.
        /// </summary>
        public whitmanenterprisewarehouseEntities1(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "whitmanenterprisewarehouseEntities1")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for whitmanenterpriseappraisal in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<whitmanenterpriseappraisal> whitmanenterpriseappraisal
        {
            get
            {
                if ((this._whitmanenterpriseappraisal == null))
                {
                    this._whitmanenterpriseappraisal = base.CreateQuery<whitmanenterpriseappraisal>("[whitmanenterpriseappraisal]");
                }
                return this._whitmanenterpriseappraisal;
            }
        }
        private global::System.Data.Objects.ObjectQuery<whitmanenterpriseappraisal> _whitmanenterpriseappraisal;
        /// <summary>
        /// There are no comments for whitmanenterpriseappraisal in the schema.
        /// </summary>
        public void AddTowhitmanenterpriseappraisal(whitmanenterpriseappraisal whitmanenterpriseappraisal)
        {
            base.AddObject("whitmanenterpriseappraisal", whitmanenterpriseappraisal);
        }
    }
    /// <summary>
    /// There are no comments for whitmanenterprisewarehouseModel1.whitmanenterpriseappraisal in the schema.
    /// </summary>
    /// <KeyProperties>
    /// idAppraisal
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="whitmanenterprisewarehouseModel1", Name="whitmanenterpriseappraisal")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class whitmanenterpriseappraisal : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new whitmanenterpriseappraisal object.
        /// </summary>
        /// <param name="idAppraisal">Initial value of idAppraisal.</param>
        public static whitmanenterpriseappraisal Createwhitmanenterpriseappraisal(int idAppraisal)
        {
            whitmanenterpriseappraisal whitmanenterpriseappraisal = new whitmanenterpriseappraisal();
            whitmanenterpriseappraisal.idAppraisal = idAppraisal;
            return whitmanenterpriseappraisal;
        }
        /// <summary>
        /// There are no comments for Property idAppraisal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int idAppraisal
        {
            get
            {
                return this._idAppraisal;
            }
            set
            {
                this.OnidAppraisalChanging(value);
                this.ReportPropertyChanging("idAppraisal");
                this._idAppraisal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idAppraisal");
                this.OnidAppraisalChanged();
            }
        }
        private int _idAppraisal;
        partial void OnidAppraisalChanging(int value);
        partial void OnidAppraisalChanged();
        /// <summary>
        /// There are no comments for Property ModelYear in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ModelYear
        {
            get
            {
                return this._ModelYear;
            }
            set
            {
                this.OnModelYearChanging(value);
                this.ReportPropertyChanging("ModelYear");
                this._ModelYear = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModelYear");
                this.OnModelYearChanged();
            }
        }
        private global::System.Nullable<int> _ModelYear;
        partial void OnModelYearChanging(global::System.Nullable<int> value);
        partial void OnModelYearChanged();
        /// <summary>
        /// There are no comments for Property Make in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this._Make;
            }
            set
            {
                this.OnMakeChanging(value);
                this.ReportPropertyChanging("Make");
                this._Make = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Make");
                this.OnMakeChanged();
            }
        }
        private string _Make;
        partial void OnMakeChanging(string value);
        partial void OnMakeChanged();
        /// <summary>
        /// There are no comments for Property Model in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this.OnModelChanging(value);
                this.ReportPropertyChanging("Model");
                this._Model = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Model");
                this.OnModelChanged();
            }
        }
        private string _Model;
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        /// <summary>
        /// There are no comments for Property Trim in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Trim
        {
            get
            {
                return this._Trim;
            }
            set
            {
                this.OnTrimChanging(value);
                this.ReportPropertyChanging("Trim");
                this._Trim = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Trim");
                this.OnTrimChanged();
            }
        }
        private string _Trim;
        partial void OnTrimChanging(string value);
        partial void OnTrimChanged();
        /// <summary>
        /// There are no comments for Property VINNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VINNumber
        {
            get
            {
                return this._VINNumber;
            }
            set
            {
                this.OnVINNumberChanging(value);
                this.ReportPropertyChanging("VINNumber");
                this._VINNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("VINNumber");
                this.OnVINNumberChanged();
            }
        }
        private string _VINNumber;
        partial void OnVINNumberChanging(string value);
        partial void OnVINNumberChanged();
        /// <summary>
        /// There are no comments for Property StockNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StockNumber
        {
            get
            {
                return this._StockNumber;
            }
            set
            {
                this.OnStockNumberChanging(value);
                this.ReportPropertyChanging("StockNumber");
                this._StockNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StockNumber");
                this.OnStockNumberChanged();
            }
        }
        private string _StockNumber;
        partial void OnStockNumberChanging(string value);
        partial void OnStockNumberChanged();
        /// <summary>
        /// There are no comments for Property SalePrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SalePrice
        {
            get
            {
                return this._SalePrice;
            }
            set
            {
                this.OnSalePriceChanging(value);
                this.ReportPropertyChanging("SalePrice");
                this._SalePrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SalePrice");
                this.OnSalePriceChanged();
            }
        }
        private string _SalePrice;
        partial void OnSalePriceChanging(string value);
        partial void OnSalePriceChanged();
        /// <summary>
        /// There are no comments for Property MSRP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MSRP
        {
            get
            {
                return this._MSRP;
            }
            set
            {
                this.OnMSRPChanging(value);
                this.ReportPropertyChanging("MSRP");
                this._MSRP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MSRP");
                this.OnMSRPChanged();
            }
        }
        private string _MSRP;
        partial void OnMSRPChanging(string value);
        partial void OnMSRPChanged();
        /// <summary>
        /// There are no comments for Property Mileage in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Mileage
        {
            get
            {
                return this._Mileage;
            }
            set
            {
                this.OnMileageChanging(value);
                this.ReportPropertyChanging("Mileage");
                this._Mileage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Mileage");
                this.OnMileageChanged();
            }
        }
        private string _Mileage;
        partial void OnMileageChanging(string value);
        partial void OnMileageChanged();
        /// <summary>
        /// There are no comments for Property Cylinders in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Cylinders
        {
            get
            {
                return this._Cylinders;
            }
            set
            {
                this.OnCylindersChanging(value);
                this.ReportPropertyChanging("Cylinders");
                this._Cylinders = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Cylinders");
                this.OnCylindersChanged();
            }
        }
        private string _Cylinders;
        partial void OnCylindersChanging(string value);
        partial void OnCylindersChanged();
        /// <summary>
        /// There are no comments for Property ExteriorColor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ExteriorColor
        {
            get
            {
                return this._ExteriorColor;
            }
            set
            {
                this.OnExteriorColorChanging(value);
                this.ReportPropertyChanging("ExteriorColor");
                this._ExteriorColor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ExteriorColor");
                this.OnExteriorColorChanged();
            }
        }
        private string _ExteriorColor;
        partial void OnExteriorColorChanging(string value);
        partial void OnExteriorColorChanged();
        /// <summary>
        /// There are no comments for Property InteriorColor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string InteriorColor
        {
            get
            {
                return this._InteriorColor;
            }
            set
            {
                this.OnInteriorColorChanging(value);
                this.ReportPropertyChanging("InteriorColor");
                this._InteriorColor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("InteriorColor");
                this.OnInteriorColorChanged();
            }
        }
        private string _InteriorColor;
        partial void OnInteriorColorChanging(string value);
        partial void OnInteriorColorChanged();
        /// <summary>
        /// There are no comments for Property InteriorSurface in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string InteriorSurface
        {
            get
            {
                return this._InteriorSurface;
            }
            set
            {
                this.OnInteriorSurfaceChanging(value);
                this.ReportPropertyChanging("InteriorSurface");
                this._InteriorSurface = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("InteriorSurface");
                this.OnInteriorSurfaceChanged();
            }
        }
        private string _InteriorSurface;
        partial void OnInteriorSurfaceChanging(string value);
        partial void OnInteriorSurfaceChanged();
        /// <summary>
        /// There are no comments for Property BodyType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyType
        {
            get
            {
                return this._BodyType;
            }
            set
            {
                this.OnBodyTypeChanging(value);
                this.ReportPropertyChanging("BodyType");
                this._BodyType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BodyType");
                this.OnBodyTypeChanged();
            }
        }
        private string _BodyType;
        partial void OnBodyTypeChanging(string value);
        partial void OnBodyTypeChanged();
        /// <summary>
        /// There are no comments for Property EngineType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EngineType
        {
            get
            {
                return this._EngineType;
            }
            set
            {
                this.OnEngineTypeChanging(value);
                this.ReportPropertyChanging("EngineType");
                this._EngineType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EngineType");
                this.OnEngineTypeChanged();
            }
        }
        private string _EngineType;
        partial void OnEngineTypeChanging(string value);
        partial void OnEngineTypeChanged();
        /// <summary>
        /// There are no comments for Property DriveTrain in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DriveTrain
        {
            get
            {
                return this._DriveTrain;
            }
            set
            {
                this.OnDriveTrainChanging(value);
                this.ReportPropertyChanging("DriveTrain");
                this._DriveTrain = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DriveTrain");
                this.OnDriveTrainChanged();
            }
        }
        private string _DriveTrain;
        partial void OnDriveTrainChanging(string value);
        partial void OnDriveTrainChanged();
        /// <summary>
        /// There are no comments for Property FuelType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelType
        {
            get
            {
                return this._FuelType;
            }
            set
            {
                this.OnFuelTypeChanging(value);
                this.ReportPropertyChanging("FuelType");
                this._FuelType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FuelType");
                this.OnFuelTypeChanged();
            }
        }
        private string _FuelType;
        partial void OnFuelTypeChanging(string value);
        partial void OnFuelTypeChanged();
        /// <summary>
        /// There are no comments for Property Tranmission in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Tranmission
        {
            get
            {
                return this._Tranmission;
            }
            set
            {
                this.OnTranmissionChanging(value);
                this.ReportPropertyChanging("Tranmission");
                this._Tranmission = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tranmission");
                this.OnTranmissionChanged();
            }
        }
        private string _Tranmission;
        partial void OnTranmissionChanging(string value);
        partial void OnTranmissionChanged();
        /// <summary>
        /// There are no comments for Property Liters in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Liters
        {
            get
            {
                return this._Liters;
            }
            set
            {
                this.OnLitersChanging(value);
                this.ReportPropertyChanging("Liters");
                this._Liters = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Liters");
                this.OnLitersChanged();
            }
        }
        private string _Liters;
        partial void OnLitersChanging(string value);
        partial void OnLitersChanged();
        /// <summary>
        /// There are no comments for Property Doors in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Doors
        {
            get
            {
                return this._Doors;
            }
            set
            {
                this.OnDoorsChanging(value);
                this.ReportPropertyChanging("Doors");
                this._Doors = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Doors");
                this.OnDoorsChanged();
            }
        }
        private string _Doors;
        partial void OnDoorsChanging(string value);
        partial void OnDoorsChanged();
        /// <summary>
        /// There are no comments for Property FuelEconomyCity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelEconomyCity
        {
            get
            {
                return this._FuelEconomyCity;
            }
            set
            {
                this.OnFuelEconomyCityChanging(value);
                this.ReportPropertyChanging("FuelEconomyCity");
                this._FuelEconomyCity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FuelEconomyCity");
                this.OnFuelEconomyCityChanged();
            }
        }
        private string _FuelEconomyCity;
        partial void OnFuelEconomyCityChanging(string value);
        partial void OnFuelEconomyCityChanged();
        /// <summary>
        /// There are no comments for Property FuelEconomyHighWay in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelEconomyHighWay
        {
            get
            {
                return this._FuelEconomyHighWay;
            }
            set
            {
                this.OnFuelEconomyHighWayChanging(value);
                this.ReportPropertyChanging("FuelEconomyHighWay");
                this._FuelEconomyHighWay = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FuelEconomyHighWay");
                this.OnFuelEconomyHighWayChanged();
            }
        }
        private string _FuelEconomyHighWay;
        partial void OnFuelEconomyHighWayChanging(string value);
        partial void OnFuelEconomyHighWayChanged();
        /// <summary>
        /// There are no comments for Property Certified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> Certified
        {
            get
            {
                return this._Certified;
            }
            set
            {
                this.OnCertifiedChanging(value);
                this.ReportPropertyChanging("Certified");
                this._Certified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Certified");
                this.OnCertifiedChanged();
            }
        }
        private global::System.Nullable<bool> _Certified;
        partial void OnCertifiedChanging(global::System.Nullable<bool> value);
        partial void OnCertifiedChanged();
        /// <summary>
        /// There are no comments for Property CarsOptions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CarsOptions
        {
            get
            {
                return this._CarsOptions;
            }
            set
            {
                this.OnCarsOptionsChanging(value);
                this.ReportPropertyChanging("CarsOptions");
                this._CarsOptions = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CarsOptions");
                this.OnCarsOptionsChanged();
            }
        }
        private string _CarsOptions;
        partial void OnCarsOptionsChanging(string value);
        partial void OnCarsOptionsChanged();
        /// <summary>
        /// There are no comments for Property CarsPackages in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CarsPackages
        {
            get
            {
                return this._CarsPackages;
            }
            set
            {
                this.OnCarsPackagesChanging(value);
                this.ReportPropertyChanging("CarsPackages");
                this._CarsPackages = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CarsPackages");
                this.OnCarsPackagesChanged();
            }
        }
        private string _CarsPackages;
        partial void OnCarsPackagesChanging(string value);
        partial void OnCarsPackagesChanged();
        /// <summary>
        /// There are no comments for Property PackageDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageDescription
        {
            get
            {
                return this._PackageDescription;
            }
            set
            {
                this.OnPackageDescriptionChanging(value);
                this.ReportPropertyChanging("PackageDescription");
                this._PackageDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PackageDescription");
                this.OnPackageDescriptionChanged();
            }
        }
        private string _PackageDescription;
        partial void OnPackageDescriptionChanging(string value);
        partial void OnPackageDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Descriptions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriptions
        {
            get
            {
                return this._Descriptions;
            }
            set
            {
                this.OnDescriptionsChanging(value);
                this.ReportPropertyChanging("Descriptions");
                this._Descriptions = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Descriptions");
                this.OnDescriptionsChanged();
            }
        }
        private string _Descriptions;
        partial void OnDescriptionsChanging(string value);
        partial void OnDescriptionsChanged();
        /// <summary>
        /// There are no comments for Property CarImageUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CarImageUrl
        {
            get
            {
                return this._CarImageUrl;
            }
            set
            {
                this.OnCarImageUrlChanging(value);
                this.ReportPropertyChanging("CarImageUrl");
                this._CarImageUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CarImageUrl");
                this.OnCarImageUrlChanged();
            }
        }
        private string _CarImageUrl;
        partial void OnCarImageUrlChanging(string value);
        partial void OnCarImageUrlChanged();
        /// <summary>
        /// There are no comments for Property DealershipName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DealershipName
        {
            get
            {
                return this._DealershipName;
            }
            set
            {
                this.OnDealershipNameChanging(value);
                this.ReportPropertyChanging("DealershipName");
                this._DealershipName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DealershipName");
                this.OnDealershipNameChanged();
            }
        }
        private string _DealershipName;
        partial void OnDealershipNameChanging(string value);
        partial void OnDealershipNameChanged();
        /// <summary>
        /// There are no comments for Property DealershipAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DealershipAddress
        {
            get
            {
                return this._DealershipAddress;
            }
            set
            {
                this.OnDealershipAddressChanging(value);
                this.ReportPropertyChanging("DealershipAddress");
                this._DealershipAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DealershipAddress");
                this.OnDealershipAddressChanged();
            }
        }
        private string _DealershipAddress;
        partial void OnDealershipAddressChanging(string value);
        partial void OnDealershipAddressChanged();
        /// <summary>
        /// There are no comments for Property DealershipCity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DealershipCity
        {
            get
            {
                return this._DealershipCity;
            }
            set
            {
                this.OnDealershipCityChanging(value);
                this.ReportPropertyChanging("DealershipCity");
                this._DealershipCity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DealershipCity");
                this.OnDealershipCityChanged();
            }
        }
        private string _DealershipCity;
        partial void OnDealershipCityChanging(string value);
        partial void OnDealershipCityChanged();
        /// <summary>
        /// There are no comments for Property DealershipState in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DealershipState
        {
            get
            {
                return this._DealershipState;
            }
            set
            {
                this.OnDealershipStateChanging(value);
                this.ReportPropertyChanging("DealershipState");
                this._DealershipState = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DealershipState");
                this.OnDealershipStateChanged();
            }
        }
        private string _DealershipState;
        partial void OnDealershipStateChanging(string value);
        partial void OnDealershipStateChanged();
        /// <summary>
        /// There are no comments for Property DealershipPhone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DealershipPhone
        {
            get
            {
                return this._DealershipPhone;
            }
            set
            {
                this.OnDealershipPhoneChanging(value);
                this.ReportPropertyChanging("DealershipPhone");
                this._DealershipPhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DealershipPhone");
                this.OnDealershipPhoneChanged();
            }
        }
        private string _DealershipPhone;
        partial void OnDealershipPhoneChanging(string value);
        partial void OnDealershipPhoneChanged();
        /// <summary>
        /// There are no comments for Property DealershipId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> DealershipId
        {
            get
            {
                return this._DealershipId;
            }
            set
            {
                this.OnDealershipIdChanging(value);
                this.ReportPropertyChanging("DealershipId");
                this._DealershipId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DealershipId");
                this.OnDealershipIdChanged();
            }
        }
        private global::System.Nullable<int> _DealershipId;
        partial void OnDealershipIdChanging(global::System.Nullable<int> value);
        partial void OnDealershipIdChanged();
        /// <summary>
        /// There are no comments for Property DealerCost in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerCost
        {
            get
            {
                return this._DealerCost;
            }
            set
            {
                this.OnDealerCostChanging(value);
                this.ReportPropertyChanging("DealerCost");
                this._DealerCost = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DealerCost");
                this.OnDealerCostChanged();
            }
        }
        private string _DealerCost;
        partial void OnDealerCostChanging(string value);
        partial void OnDealerCostChanged();
        /// <summary>
        /// There are no comments for Property ACV in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ACV
        {
            get
            {
                return this._ACV;
            }
            set
            {
                this.OnACVChanging(value);
                this.ReportPropertyChanging("ACV");
                this._ACV = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ACV");
                this.OnACVChanged();
            }
        }
        private string _ACV;
        partial void OnACVChanging(string value);
        partial void OnACVChanged();
        /// <summary>
        /// There are no comments for Property DefaultImageUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultImageUrl
        {
            get
            {
                return this._DefaultImageUrl;
            }
            set
            {
                this.OnDefaultImageUrlChanging(value);
                this.ReportPropertyChanging("DefaultImageUrl");
                this._DefaultImageUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DefaultImageUrl");
                this.OnDefaultImageUrlChanged();
            }
        }
        private string _DefaultImageUrl;
        partial void OnDefaultImageUrlChanging(string value);
        partial void OnDefaultImageUrlChanged();
        /// <summary>
        /// There are no comments for Property AppraisalDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> AppraisalDate
        {
            get
            {
                return this._AppraisalDate;
            }
            set
            {
                this.OnAppraisalDateChanging(value);
                this.ReportPropertyChanging("AppraisalDate");
                this._AppraisalDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AppraisalDate");
                this.OnAppraisalDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _AppraisalDate;
        partial void OnAppraisalDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAppraisalDateChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this.ReportPropertyChanging("State");
                this._State = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("State");
                this.OnStateChanged();
            }
        }
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property ZipCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this._ZipCode;
            }
            set
            {
                this.OnZipCodeChanging(value);
                this.ReportPropertyChanging("ZipCode");
                this._ZipCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ZipCode");
                this.OnZipCodeChanged();
            }
        }
        private string _ZipCode;
        partial void OnZipCodeChanging(string value);
        partial void OnZipCodeChanged();
        /// <summary>
        /// There are no comments for Property AppraisalBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AppraisalBy
        {
            get
            {
                return this._AppraisalBy;
            }
            set
            {
                this.OnAppraisalByChanging(value);
                this.ReportPropertyChanging("AppraisalBy");
                this._AppraisalBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AppraisalBy");
                this.OnAppraisalByChanged();
            }
        }
        private string _AppraisalBy;
        partial void OnAppraisalByChanging(string value);
        partial void OnAppraisalByChanged();
        /// <summary>
        /// There are no comments for Property InventoryAdd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> InventoryAdd
        {
            get
            {
                return this._InventoryAdd;
            }
            set
            {
                this.OnInventoryAddChanging(value);
                this.ReportPropertyChanging("InventoryAdd");
                this._InventoryAdd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("InventoryAdd");
                this.OnInventoryAddChanged();
            }
        }
        private global::System.Nullable<bool> _InventoryAdd;
        partial void OnInventoryAddChanging(global::System.Nullable<bool> value);
        partial void OnInventoryAddChanged();
        /// <summary>
        /// There are no comments for Property AppraisalType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AppraisalType
        {
            get
            {
                return this._AppraisalType;
            }
            set
            {
                this.OnAppraisalTypeChanging(value);
                this.ReportPropertyChanging("AppraisalType");
                this._AppraisalType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AppraisalType");
                this.OnAppraisalTypeChanged();
            }
        }
        private string _AppraisalType;
        partial void OnAppraisalTypeChanging(string value);
        partial void OnAppraisalTypeChanged();
        /// <summary>
        /// There are no comments for Property AppraisalID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AppraisalID
        {
            get
            {
                return this._AppraisalID;
            }
            set
            {
                this.OnAppraisalIDChanging(value);
                this.ReportPropertyChanging("AppraisalID");
                this._AppraisalID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AppraisalID");
                this.OnAppraisalIDChanged();
            }
        }
        private string _AppraisalID;
        partial void OnAppraisalIDChanging(string value);
        partial void OnAppraisalIDChanged();
        /// <summary>
        /// There are no comments for Property ChromeModelId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ChromeModelId
        {
            get
            {
                return this._ChromeModelId;
            }
            set
            {
                this.OnChromeModelIdChanging(value);
                this.ReportPropertyChanging("ChromeModelId");
                this._ChromeModelId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ChromeModelId");
                this.OnChromeModelIdChanged();
            }
        }
        private string _ChromeModelId;
        partial void OnChromeModelIdChanging(string value);
        partial void OnChromeModelIdChanged();
        /// <summary>
        /// There are no comments for Property ChromeStyleId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ChromeStyleId
        {
            get
            {
                return this._ChromeStyleId;
            }
            set
            {
                this.OnChromeStyleIdChanging(value);
                this.ReportPropertyChanging("ChromeStyleId");
                this._ChromeStyleId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ChromeStyleId");
                this.OnChromeStyleIdChanged();
            }
        }
        private string _ChromeStyleId;
        partial void OnChromeStyleIdChanging(string value);
        partial void OnChromeStyleIdChanged();
        /// <summary>
        /// There are no comments for Property StandardOptions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StandardOptions
        {
            get
            {
                return this._StandardOptions;
            }
            set
            {
                this.OnStandardOptionsChanging(value);
                this.ReportPropertyChanging("StandardOptions");
                this._StandardOptions = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StandardOptions");
                this.OnStandardOptionsChanged();
            }
        }
        private string _StandardOptions;
        partial void OnStandardOptionsChanging(string value);
        partial void OnStandardOptionsChanged();
        /// <summary>
        /// There are no comments for Property LastUpdated in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return this._LastUpdated;
            }
            set
            {
                this.OnLastUpdatedChanging(value);
                this.ReportPropertyChanging("LastUpdated");
                this._LastUpdated = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastUpdated");
                this.OnLastUpdatedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();
        /// <summary>
        /// There are no comments for Property VehicleType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleType
        {
            get
            {
                return this._VehicleType;
            }
            set
            {
                this.OnVehicleTypeChanging(value);
                this.ReportPropertyChanging("VehicleType");
                this._VehicleType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("VehicleType");
                this.OnVehicleTypeChanged();
            }
        }
        private string _VehicleType;
        partial void OnVehicleTypeChanging(string value);
        partial void OnVehicleTypeChanged();
        /// <summary>
        /// There are no comments for Property TruckClass in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckClass
        {
            get
            {
                return this._TruckClass;
            }
            set
            {
                this.OnTruckClassChanging(value);
                this.ReportPropertyChanging("TruckClass");
                this._TruckClass = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TruckClass");
                this.OnTruckClassChanged();
            }
        }
        private string _TruckClass;
        partial void OnTruckClassChanging(string value);
        partial void OnTruckClassChanged();
        /// <summary>
        /// There are no comments for Property TruckType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckType
        {
            get
            {
                return this._TruckType;
            }
            set
            {
                this.OnTruckTypeChanging(value);
                this.ReportPropertyChanging("TruckType");
                this._TruckType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TruckType");
                this.OnTruckTypeChanged();
            }
        }
        private string _TruckType;
        partial void OnTruckTypeChanging(string value);
        partial void OnTruckTypeChanged();
        /// <summary>
        /// There are no comments for Property TruckCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckCategory
        {
            get
            {
                return this._TruckCategory;
            }
            set
            {
                this.OnTruckCategoryChanging(value);
                this.ReportPropertyChanging("TruckCategory");
                this._TruckCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TruckCategory");
                this.OnTruckCategoryChanged();
            }
        }
        private string _TruckCategory;
        partial void OnTruckCategoryChanging(string value);
        partial void OnTruckCategoryChanged();
        /// <summary>
        /// There are no comments for Property KBBOptionsId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string KBBOptionsId
        {
            get
            {
                return this._KBBOptionsId;
            }
            set
            {
                this.OnKBBOptionsIdChanging(value);
                this.ReportPropertyChanging("KBBOptionsId");
                this._KBBOptionsId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("KBBOptionsId");
                this.OnKBBOptionsIdChanged();
            }
        }
        private string _KBBOptionsId;
        partial void OnKBBOptionsIdChanging(string value);
        partial void OnKBBOptionsIdChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this.ReportPropertyChanging("Note");
                this._Note = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Note");
                this.OnNoteChanged();
            }
        }
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property Carfaxowner in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Carfaxowner
        {
            get
            {
                return this._Carfaxowner;
            }
            set
            {
                this.OnCarfaxownerChanging(value);
                this.ReportPropertyChanging("Carfaxowner");
                this._Carfaxowner = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Carfaxowner");
                this.OnCarfaxownerChanged();
            }
        }
        private global::System.Nullable<int> _Carfaxowner;
        partial void OnCarfaxownerChanging(global::System.Nullable<int> value);
        partial void OnCarfaxownerChanged();
        /// <summary>
        /// There are no comments for Property KBBTrimId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> KBBTrimId
        {
            get
            {
                return this._KBBTrimId;
            }
            set
            {
                this.OnKBBTrimIdChanging(value);
                this.ReportPropertyChanging("KBBTrimId");
                this._KBBTrimId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("KBBTrimId");
                this.OnKBBTrimIdChanged();
            }
        }
        private global::System.Nullable<int> _KBBTrimId;
        partial void OnKBBTrimIdChanging(global::System.Nullable<int> value);
        partial void OnKBBTrimIdChanged();
        /// <summary>
        /// There are no comments for Property Signature in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Signature
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Signature);
            }
            set
            {
                this.OnSignatureChanging(value);
                this.ReportPropertyChanging("Signature");
                this._Signature = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Signature");
                this.OnSignatureChanged();
            }
        }
        private byte[] _Signature;
        partial void OnSignatureChanging(byte[] value);
        partial void OnSignatureChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this.ReportPropertyChanging("Street");
                this._Street = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Street");
                this.OnStreetChanged();
            }
        }
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property Photo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Photo);
            }
            set
            {
                this.OnPhotoChanging(value);
                this.ReportPropertyChanging("Photo");
                this._Photo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Photo");
                this.OnPhotoChanged();
            }
        }
        private byte[] _Photo;
        partial void OnPhotoChanging(byte[] value);
        partial void OnPhotoChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property VinGenie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> VinGenie
        {
            get
            {
                return this._VinGenie;
            }
            set
            {
                this.OnVinGenieChanging(value);
                this.ReportPropertyChanging("VinGenie");
                this._VinGenie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("VinGenie");
                this.OnVinGenieChanged();
            }
        }
        private global::System.Nullable<bool> _VinGenie;
        partial void OnVinGenieChanging(global::System.Nullable<bool> value);
        partial void OnVinGenieChanged();
        /// <summary>
        /// There are no comments for Property UserStamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserStamp
        {
            get
            {
                return this._UserStamp;
            }
            set
            {
                this.OnUserStampChanging(value);
                this.ReportPropertyChanging("UserStamp");
                this._UserStamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserStamp");
                this.OnUserStampChanged();
            }
        }
        private string _UserStamp;
        partial void OnUserStampChanging(string value);
        partial void OnUserStampChanged();
        /// <summary>
        /// There are no comments for Property DateStamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateStamp
        {
            get
            {
                return this._DateStamp;
            }
            set
            {
                this.OnDateStampChanging(value);
                this.ReportPropertyChanging("DateStamp");
                this._DateStamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateStamp");
                this.OnDateStampChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateStamp;
        partial void OnDateStampChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateStampChanged();
        /// <summary>
        /// There are no comments for Property NumberOfCar in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> NumberOfCar
        {
            get
            {
                return this._NumberOfCar;
            }
            set
            {
                this.OnNumberOfCarChanging(value);
                this.ReportPropertyChanging("NumberOfCar");
                this._NumberOfCar = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NumberOfCar");
                this.OnNumberOfCarChanged();
            }
        }
        private global::System.Nullable<int> _NumberOfCar;
        partial void OnNumberOfCarChanging(global::System.Nullable<int> value);
        partial void OnNumberOfCarChanged();
        /// <summary>
        /// There are no comments for Property CarRanking in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CarRanking
        {
            get
            {
                return this._CarRanking;
            }
            set
            {
                this.OnCarRankingChanging(value);
                this.ReportPropertyChanging("CarRanking");
                this._CarRanking = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CarRanking");
                this.OnCarRankingChanged();
            }
        }
        private global::System.Nullable<int> _CarRanking;
        partial void OnCarRankingChanging(global::System.Nullable<int> value);
        partial void OnCarRankingChanged();
        /// <summary>
        /// There are no comments for Property DeviceId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId
        {
            get
            {
                return this._DeviceId;
            }
            set
            {
                this.OnDeviceIdChanging(value);
                this.ReportPropertyChanging("DeviceId");
                this._DeviceId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DeviceId");
                this.OnDeviceIdChanged();
            }
        }
        private string _DeviceId;
        partial void OnDeviceIdChanging(string value);
        partial void OnDeviceIdChanged();
        /// <summary>
        /// There are no comments for Property DeviceName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName
        {
            get
            {
                return this._DeviceName;
            }
            set
            {
                this.OnDeviceNameChanging(value);
                this.ReportPropertyChanging("DeviceName");
                this._DeviceName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DeviceName");
                this.OnDeviceNameChanged();
            }
        }
        private string _DeviceName;
        partial void OnDeviceNameChanging(string value);
        partial void OnDeviceNameChanged();
        /// <summary>
        /// There are no comments for Property MarketLowestPrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> MarketLowestPrice
        {
            get
            {
                return this._MarketLowestPrice;
            }
            set
            {
                this.OnMarketLowestPriceChanging(value);
                this.ReportPropertyChanging("MarketLowestPrice");
                this._MarketLowestPrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MarketLowestPrice");
                this.OnMarketLowestPriceChanged();
            }
        }
        private global::System.Nullable<decimal> _MarketLowestPrice;
        partial void OnMarketLowestPriceChanging(global::System.Nullable<decimal> value);
        partial void OnMarketLowestPriceChanged();
        /// <summary>
        /// There are no comments for Property MarketAveragePrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> MarketAveragePrice
        {
            get
            {
                return this._MarketAveragePrice;
            }
            set
            {
                this.OnMarketAveragePriceChanging(value);
                this.ReportPropertyChanging("MarketAveragePrice");
                this._MarketAveragePrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MarketAveragePrice");
                this.OnMarketAveragePriceChanged();
            }
        }
        private global::System.Nullable<decimal> _MarketAveragePrice;
        partial void OnMarketAveragePriceChanging(global::System.Nullable<decimal> value);
        partial void OnMarketAveragePriceChanged();
        /// <summary>
        /// There are no comments for Property MarketHighestPrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> MarketHighestPrice
        {
            get
            {
                return this._MarketHighestPrice;
            }
            set
            {
                this.OnMarketHighestPriceChanging(value);
                this.ReportPropertyChanging("MarketHighestPrice");
                this._MarketHighestPrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MarketHighestPrice");
                this.OnMarketHighestPriceChanged();
            }
        }
        private global::System.Nullable<decimal> _MarketHighestPrice;
        partial void OnMarketHighestPriceChanging(global::System.Nullable<decimal> value);
        partial void OnMarketHighestPriceChanged();
        /// <summary>
        /// There are no comments for Property ColorCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorCode
        {
            get
            {
                return this._ColorCode;
            }
            set
            {
                this.OnColorCodeChanging(value);
                this.ReportPropertyChanging("ColorCode");
                this._ColorCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ColorCode");
                this.OnColorCodeChanged();
            }
        }
        private string _ColorCode;
        partial void OnColorCodeChanging(string value);
        partial void OnColorCodeChanged();
    }
}
