//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinCLAPP.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.SelectedCities = new HashSet<SelectedCity>();
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public string CraigsListCityURL { get; set; }
        public Nullable<short> SubCity { get; set; }
        public Nullable<int> CLIndex { get; set; }
        public string State { get; set; }
        public string StateAbbr { get; set; }
        public string AreaAbbr { get; set; }
        public string SubAbbr { get; set; }
    
        public virtual ICollection<SelectedCity> SelectedCities { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}
