//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinCLAPP.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLDMSEntities : DbContext
    {
        public CLDMSEntities()
            : base("name=CLDMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<DataFeedVendor> DataFeedVendors { get; set; }
        public DbSet<Dealer> Dealers { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Package> Packages { get; set; }
        public DbSet<SelectedCity> SelectedCities { get; set; }
        public DbSet<SoldOutInventory> SoldOutInventories { get; set; }
        public DbSet<Tracking> Trackings { get; set; }
        public DbSet<UsaZipCode> UsaZipCodes { get; set; }
        public DbSet<WheelDrive> WheelDrives { get; set; }
    }
}
