//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinCLAPP.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> MonthlyPrice { get; set; }
        public string Period { get; set; }
        public Nullable<int> TotalCharge { get; set; }
        public Nullable<int> QuickBookPackageId { get; set; }
        public string QuickBookPackageName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
