//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinCLAPP.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WheelDrive
    {
        public int WheelDriveId { get; set; }
        public string Name { get; set; }
        public string TextValue { get; set; }
        public string ShortValue { get; set; }
    }
}
