//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinCLAPP.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public Dealer()
        {
            this.Inventories = new HashSet<Inventory>();
            this.SelectedCities = new HashSet<SelectedCity>();
            this.SoldOutInventories = new HashSet<SoldOutInventory>();
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int DealerId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string LogoURL { get; set; }
        public string WebSiteURL { get; set; }
        public string CreditURL { get; set; }
        public string LeadEmail { get; set; }
        public Nullable<int> EmailFormat { get; set; }
        public string CityOveride { get; set; }
        public string DealerTitle { get; set; }
        public Nullable<int> DelayTimer { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> ExceptionCategory { get; set; }
        public string GoogleAnalyticAccount { get; set; }
        public string DealerPathFeed { get; set; }
        public string DataFeedVendor { get; set; }
        public string VendorEmail { get; set; }
        public string VendorPhone { get; set; }
        public string CustomMessage { get; set; }
        public string AuthorizedName { get; set; }
        public string EndingSentence { get; set; }
        public Nullable<bool> PostWithPrice { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<SelectedCity> SelectedCities { get; set; }
        public virtual ICollection<SoldOutInventory> SoldOutInventories { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}
