//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinCLAPP.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedCity
    {
        public int DealerId { get; set; }
        public int AccountId { get; set; }
        public int CityId { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual City City { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
