//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinCLAPP.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int TrackingId { get; set; }
        public Nullable<long> CLPostingId { get; set; }
        public Nullable<int> ListingId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Computer { get; set; }
        public string EmailAccount { get; set; }
        public string AdsUrl { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual City City { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
